version: '2.0'
services: 
    conan-backend:
        build:
            context: './conan-backend'
            dockerfile: './Dockerfile'
        container_name: 'conan-backend'
        ports: 
            - ${PORT_API}:${PORT_API}
        volumes: 
            - './conan-backend/src:/conan-backend/src'
        env_file: 
            - './.env'
        depends_on: 
            - "conan-mysql"
    conan-mysql:
        build:
            context: './conan-mysql'
            dockerfile: './Dockerfile'
        container_name: 'conan-mysql'
        ports:
            - ${PORT_MYSQL}:${PORT_MYSQL}
        env_file:
            - ".env"
    conan-web:
        build: 
            context: './conan-web'
            dockerfile: './Dockerfile'
        container_name: 'conan-web'
        ports:
            - ${PORT_WEB}:${PORT_WEB}
        volumes:
            - './conan-web/src/express:/conan-web/src/express'
            - './conan-react/build:/conan-web/dist/public/build'
        env_file:
            - ".env"
        depends_on: 
            - "conan-backend"
