CREATE TABLE IF NOT EXISTS `Session` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    created_at DATETIME
);

CREATE TABLE IF NOT EXISTS Position (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sessionId INT NOT NULL,
    x DOUBLE(12, 6) NOT NULL,
    y DOUBLE(12, 6) NOT NULL,
    read_at INT NOT NULL,
    created_at DATETIME,
    rotation INT UNSIGNED NOT NULL,
    FOREIGN KEY (sessionId) REFERENCES `Session`(id)
);

CREATE TABLE IF NOT EXISTS Collision (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    positionId INT NOT NULL,
    FOREIGN KEY (positionId) REFERENCES `Position`(id)
);